### ISSUE TITLE
Multiple Catalog Connection

### ISSUE THREAD

**Issue by asheeshgarg** [apache/iceberg-python#156]
### Question

From pyiceberg if I want to connect to multiple catalogs we need to create a seperate instance per catalog or there is option to specify multiple catalogs as part of the config?

**Comment by Fokko** [comment]
Hey @asheeshgarg You can already do this. 

The configuration in `~/.pyiceberg.yaml`:
```yaml
catalog:
    hive:
        uri: thrift://127.0.0.1:9083
        s3.endpoint: http://127.0.0.1:9000
        s3.access-key-id: admin
        s3.secret-access-key: password

    rest:
        uri: https://rest-server:8181/
        warehouse: Fokko
```

In Python you can load the different catalogs like this:

```python
from pyiceberg.catalog import load_catalog

hive = load_catalog('hive')
rest = load_catalog('rest')
```
