### ISSUE TITLE
[BUG] CLI fails with Glue catalog because of missing URI

### ISSUE THREAD

**Issue by stefnba** [apache/iceberg-python#255]
### Apache Iceberg version

0.5.0 (latest release)

### Please describe the bug 🐞

Hi all

I have the following config in a `~/.pyiceberg.yaml` to interact with a Glue catalog via the command line.

```yaml
catalog:
  default:
    type: glue
    aws_access_key_id: <ACCESS_KEY_ID>
    aws_secret_access_key: <SECRET_ACCESS_KEY>
    region_name: <REGION_NAME>
```

However, when running any command on the command line, e.g. `pyiceberg list` the following error appears: 

`URI missing, please provide using --uri, the config or environment variable PYICEBERG_CATALOG__DEFAULT__URI`

As far as I know, Glue doesn't require a `URI`. Also when using pyiceberg and this config within a notebook, everything works fine.
