### ISSUE TITLE
Cannot create table if location/endpoint is s3 on a "secure" Minio server

### ISSUE THREAD

**Issue by thinkORo** [apache/iceberg-python#540]
### Apache Iceberg version

0.6.0 (latest release)

### Please describe the bug 🐞

I've create a .pyiceberg.yaml file with the following content:

```
catalog:
  default:
    s3.endpoint: https://localhost:9199
    s3.access-key-id: iceberg
    s3.secret-access-key: iceberg123
    s3.region: us-east-1
    type: sql
    uri: postgresql+psycopg2://iceberg:iceberg123@localhost:5432/iceberg
```

My code is like this:

```
from pyiceberg.catalog import load_catalog
import pyarrow.parquet as pq

catalog = load_catalog('default')
df = pq.read_table("yellow_tripdata_2023-01.parquet")

catalog.create_namespace("demo")
table = catalog.create_table(
    "demo.taxi_dataset",
    schema=df.schema,
    location="s3://iceberg",
)
```
If I'd change the location from s3 to any location on my local drive (like: /tmp/iceberg) everything works fine. But with S3 I'd get the following error:

```
OSError: When getting information for key 'metadata/00000-97670b6c-f2c1-45a0-8026-b47087f28abe.metadata.json' in bucket 'iceberg': AWS Error NETWORK_CONNECTION during HeadObject operation: curlCode: 60, SSL peer certificate or SSH remote key was not OK
```

I didn't find any solution to handle this issue. Could one please give me some advices?
